import { execFileSync, spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import type { WorktreeBinding } from '../worktrees.js';

/**
 * Pre-provision a writable Flutter toolchain inside the job handoff.
 *
 * Why: the `workspace` sandbox allows host *reads* but confines *writes* to the
 * handoff cwd + temp. Flutter writes as it runs — `$FLUTTER_ROOT/bin/cache`,
 * `$PUB_CACHE`, `$HOME/.dart-tool` — so an agent pointed at `~/fvm/versions/<pin>`
 * cannot run `flutter test` at all. Observed 2026-08-17 in bjob_msws7z98_k8m9,
 * where the agent hand-built a symlink SDK overlay to work around it and then
 * verified the fix with widget renders instead of the project's real gate.
 *
 * The clone is APFS copy-on-write (`cp -Rc`): ~12s for a 2.0G SDK and near-zero
 * disk until something diverges. It inherits the host SDK's already-populated
 * `bin/cache`, so no download or precache step is needed.
 */

export type ToolchainProvision = {
  /** Extra env merged into the agent process. */
  env: Record<string, string>;
  /** Lines describing the toolchain for BRIEF.md / the agent prompt. */
  notes: string[];
  /** True when an SDK was actually provisioned. */
  ok: boolean;
};

export const NO_TOOLCHAIN: ToolchainProvision = { env: {}, notes: [], ok: false };

type Log = (line: string, level?: 'info' | 'warn' | 'error') => void;

/** Flutter version pinned by the repo (`.fvmrc`), if any. */
function readFvmPin(worktreeAbs: string): string | null {
  const file = path.join(worktreeAbs, '.fvmrc');
  if (!existsSync(file)) return null;
  try {
    const raw = JSON.parse(readFileSync(file, 'utf8')) as { flutter?: unknown };
    const pin = String(raw.flutter ?? '').trim();
    // Version dirs are user-supplied; keep them to a safe leaf name.
    return /^[A-Za-z0-9._-]+$/.test(pin) ? pin : null;
  } catch {
    return null;
  }
}

function fvmVersionsRoot(): string {
  const home = process.env.FVM_HOME?.trim();
  return home ? path.join(home, 'versions') : path.join(os.homedir(), 'fvm', 'versions');
}

/** `flutter`/`dart` shims that set the sandbox-writable env, then exec the clone. */
function writeShims(binDir: string, sdkDir: string, homeDir: string, pubCache: string): void {
  mkdirSync(binDir, { recursive: true });
  for (const tool of ['flutter', 'dart'] as const) {
    const shim = path.join(binDir, tool);
    writeFileSync(
      shim,
      [
        '#!/bin/sh',
        '# Generated by Defect Drainer — pre-provisioned toolchain for this job.',
        `export FLUTTER_ROOT=${JSON.stringify(sdkDir)}`,
        `export PUB_CACHE=${JSON.stringify(pubCache)}`,
        // HOME is redirected for the SDK only, so the agent's own ~/.grok stays put.
        `export HOME=${JSON.stringify(homeDir)}`,
        'export FLUTTER_SUPPRESS_ANALYTICS=true',
        `exec ${JSON.stringify(path.join(sdkDir, 'bin', tool))} "$@"`,
        '',
      ].join('\n'),
      'utf8',
    );
    chmodSync(shim, 0o755);
  }
}

/**
 * Clone the pinned SDK into `<handoff>/.tooling` and return env + brief notes.
 * Never throws: a failed provision downgrades to "agent has no toolchain",
 * which is the pre-existing behaviour, not a job failure.
 */
export function provisionFlutterToolchain(opts: {
  handoffAbs: string;
  worktrees: WorktreeBinding[];
  onLog: Log;
}): ToolchainProvision {
  const { handoffAbs, worktrees, onLog } = opts;

  const pinned = worktrees
    .map((w) => ({ repo: w.repo, abs: w.worktreeAbs, pin: readFvmPin(w.worktreeAbs) }))
    .filter((p): p is { repo: string; abs: string; pin: string } => !!p.pin);

  if (!pinned.length) {
    onLog('toolchain=flutter but no worktree pins one (.fvmrc) — skipped', 'warn');
    return NO_TOOLCHAIN;
  }

  const pins = [...new Set(pinned.map((p) => p.pin))];
  if (pins.length > 1) {
    onLog(
      `toolchain: worktrees pin conflicting Flutter versions (${pins.join(', ')}) — skipped`,
      'warn',
    );
    return NO_TOOLCHAIN;
  }

  const pin = pins[0]!;
  const source = path.join(fvmVersionsRoot(), pin);
  if (!existsSync(source)) {
    onLog(
      `toolchain: Flutter ${pin} is not installed on the host (${source}) — skipped. Run \`fvm install ${pin}\`.`,
      'warn',
    );
    return NO_TOOLCHAIN;
  }

  const tooling = path.join(handoffAbs, '.tooling');
  const sdkDir = path.join(tooling, 'flutter-sdk');
  const homeDir = path.join(tooling, 'home');
  const pubCache = path.join(tooling, 'pub-cache');
  const binDir = path.join(tooling, 'bin');

  try {
    mkdirSync(tooling, { recursive: true });
    mkdirSync(homeDir, { recursive: true });
    mkdirSync(pubCache, { recursive: true });

    const started = Date.now();
    // -c clones on APFS; cp falls back to a full copy elsewhere (slower, but correct).
    execFileSync('cp', ['-Rc', source, sdkDir], { stdio: 'pipe' });
    const secs = ((Date.now() - started) / 1000).toFixed(1);

    writeShims(binDir, sdkDir, homeDir, pubCache);

    // Prove the clone runs before promising it to the agent.
    const probe = spawnSync(path.join(binDir, 'flutter'), ['--version'], {
      encoding: 'utf8',
      timeout: 180_000,
    });
    if (probe.status !== 0) {
      const why = (probe.stderr || probe.stdout || `exit ${probe.status}`).trim().split('\n')[0];
      onLog(`toolchain: provisioned SDK failed its probe — skipped (${why})`, 'warn');
      return NO_TOOLCHAIN;
    }

    onLog(`toolchain: Flutter ${pin} cloned → ${sdkDir} in ${secs}s (APFS clone, shims in .tooling/bin)`);

    return {
      ok: true,
      env: { PATH: `${binDir}:${process.env.PATH ?? ''}` },
      notes: [
        `TOOLCHAIN: Flutter ${pin} is pre-provisioned and writable for this job.`,
        `- Run \`flutter\` / \`dart\` directly (shims at ${binDir} are first on PATH).`,
        `- Do NOT use \`fvm\`, install another SDK, or build an SDK overlay — writes to ~/fvm are blocked and unnecessary here.`,
        `- The project's own test/analyze/gate commands are expected to run; report exit codes in fix-notes.`,
      ],
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    onLog(`toolchain: provisioning failed — skipped (${msg})`, 'warn');
    return NO_TOOLCHAIN;
  }
}
