import { mkdirSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

/**
 * Per-job grok sandbox profile (`<handoff>/.grok/sandbox.toml`).
 *
 * The built-in `workspace` profile reads everywhere but writes only to cwd,
 * /tmp and ~/.grok — so `simctl install` (which writes into the CoreSimulator
 * device tree) fails, and an agent can only produce widget renders instead of
 * real on-device screenshots. grok supports custom profiles that extend a
 * built-in one with extra `read_write` grants; DD writes one into the handoff
 * so the grant is scoped to a single job and never edits the operator's global
 * ~/.grok/sandbox.toml.
 *
 * Opt-in per app (App Settings → Simulator writes). Default off: this widens
 * what a coding agent may modify on the host.
 */

/** Simulator device data — what `simctl install` / app launches write to. */
function simulatorDevicesDir(): string {
  return path.join(os.homedir(), 'Library', 'Developer', 'CoreSimulator', 'Devices');
}

export type SandboxProfileResult = {
  /** Profile name to pass to `--sandbox`; the built-in name when nothing was added. */
  profile: string;
  notes: string[];
};

/**
 * Write a job-scoped profile granting Simulator writes on top of `base`.
 * `read_write` takes literal directory grants (no globs).
 */
export function writeSimulatorSandboxProfile(opts: {
  handoffAbs: string;
  base: 'workspace' | 'strict';
  batchId: string;
}): SandboxProfileResult {
  const name = 'dd-simulator';
  const devices = simulatorDevicesDir();
  const dir = path.join(opts.handoffAbs, '.grok');
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    path.join(dir, 'sandbox.toml'),
    [
      `# Generated by Defect Drainer for ${opts.batchId} — job-scoped, not global.`,
      `[profiles.${name}]`,
      `extends = ${JSON.stringify(opts.base)}`,
      `read_write = [${JSON.stringify(devices)}]`,
      '',
    ].join('\n'),
    'utf8',
  );
  return {
    profile: name,
    notes: [
      `SIMULATOR: this job may write to the iOS Simulator device tree (${devices}).`,
      `- Real app installs/launches are allowed: prefer simctl screenshots of the running app over widget-test renders.`,
      `- Nothing else on the host became writable.`,
    ],
  };
}
